### ISSUE TITLE
Elislint issues in mobile.js

### ISSUE THREAD

**Issue by marcusgreen** [rezeau/moodle-qtype_answersselect#1]
ESLint errors as commented in this discussion, Not essential as it doesn't stop the code working but it is nice to conform to the standards.
https://moodle.org/mod/forum/discuss.php?d=425286#p1712722
(#43) 'i' is defined but never used. (no-unused-vars)
Removed the i variable, tested in the mobile emulator and appears to work as expected.
(#72) Expected an assignment or function call and instead saw an expression. (no-unused-expressions)
/* eslint-disable-next-line */
result;
Will now try to create a pull request for this.

**Comment by rezeau** [comment]
Hi Marcus, no need for a PR I've just fixed this in version 1.3 just uploaded!

**Comment by marcusgreen** [comment]
Great minds think alike!
