### ISSUE TITLE
ESLint complains about blank spaces

### ISSUE THREAD

**Issue by marcusgreen** [rezeau/moodle-qtype_answersselect#3]
It makes no difference to anything but ESLInt but it is complaining about the blank space on line 69.
Of course no human would notice as its just a blank space :(
I have my VSCode set to trim those spaces. Feel free to close this as entirely unimportant.
https://github.com/rezeau/moodle-qtype_answersselect/blob/358c378fe68f53f647e71823f97b39d09f3f8a21/mobile/answersselect.js#L69

**Comment by rezeau** [comment]
Thanks for spotting that. I'll make a note and fix it alongwith other pbs in a further release...
